slogan: "思维世界的发展，在某种意义上说，就是对惊奇的不断摆脱。——爱因斯坦"

menu:
  - title: 归档
    url: archives
    intro: "所有文章"
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "所有类别"
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "所有标签"
    icon: "fa fa-tags"
  - title: 关于
    url: about
    intro: "关于"
    icon: "fa fa-user"

links:
  - title: "Github"
    url: http://www.github.com/dabing1022
    intro: "ChildhoodAndyGithub"
    icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: atom.xml
fancybox: true
favicon: favicon.png
duoshuo_shortname: ChildhoodAndy
google_analytics: false
qq_analytics: true